apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorial-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: factorial
  template:
    metadata:
      labels:
        component: factorial
    spec:
      containers:
        - name: factorial
          image: makarovvv/factorial
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
          env:
            - name: RMQ_URL
              value: amqp://rabbitmq-cluster-ip-service
            - name: RMQ_FIBONACCI_QUEUE
              value: fibonacci_queue
            - name: RMQ_FACTORIAL_QUEUE
              value: factorial_queue

